=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BrexitServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BrexitServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BrexitServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BrexitServicesApi' do
    it 'should create an instance of BrexitServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BrexitServicesApi)
    end
  end

  # unit tests for pic_v1_brexit_invoices_post
  # Invoices
  # Invoices
  # @param authorization Bearer token obtained from SSO
  # @param file Invoice to save.
  # @param ref Reference code. Example: 866075/4SHZQ6YLMEJ7BF
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :business_unit Business Unit code: Example: 80
  # @option opts [Integer] :account_number Account Number. Example: 20855
  # @option opts [BOOLEAN] :sandbox enables sandbox mode
  # @return [InvoiceResponse]
  describe 'pic_v1_brexit_invoices_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for pic_v1_brexit_tariff_item_post
  # Tariff Items
  # Tariff Items
  # @param authorization Bearer token obtained from SSO
  # @param input Tariff Item
  # @param [Hash] opts the optional parameters
  # @return [TariffItemResponse]
  describe 'pic_v1_brexit_tariff_item_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
