=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CitiesServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CitiesServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CitiesServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CitiesServicesApi' do
    it 'should create an instance of CitiesServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CitiesServicesApi)
    end
  end

  # unit tests for pic_v1_cities_get
  # Filter cities
  # Filter cities by country, postal code and city name
  # @param authorization Bearer token obtained from SSO
  # @param country_code Country code. Example : \&quot;ES\&quot;
  # @param postal_code Postal code. Example : \&quot;47001\&quot;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :city_name City name. Example : \&quot;Valladolid\&quot;
  # @return [CitiesResponse]
  describe 'pic_v1_cities_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
