=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CustomsServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomsServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CustomsServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomsServicesApi' do
    it 'should create an instance of CustomsServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CustomsServicesApi)
    end
  end

  # unit tests for pic_v1_customs_get
  # Customs services
  # Customs services by originDepot, destinationDepot, serviceCode, shipmentType, shipmentWeight and shipmentValue 
  # @param authorization Bearer token obtained from SSO
  # @param origin_depot Origin Depot. Example: \&quot;47\&quot;
  # @param destination_depot Destination Depot. Example: \&quot;52\&quot;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :service_code Service Code. Example: \&quot;1\&quot;
  # @option opts [String] :shipment_type shipment Type. Example: \&quot;D\&quot;
  # @option opts [String] :shipment_weight Shipment Weight. Example: \&quot;16\&quot;
  # @option opts [String] :shipment_value Shipment Value. Example: \&quot;160
  # @return [CustomsResponse]
  describe 'pic_v1_customs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
