=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DeliveryManifestServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeliveryManifestServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DeliveryManifestServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeliveryManifestServicesApi' do
    it 'should create an instance of DeliveryManifestServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DeliveryManifestServicesApi)
    end
  end

  # unit tests for pic_v1_shipments_delivery_manifest_get
  # Manifest generation
  # Manifest generation
  # @param authorization Bearer token obtained from SSO
  # @param nif NIF. Example: B03260684
  # @param [Hash] opts the optional parameters
  # @option opts [String] :ccc Cost Center. Example: 20855
  # @option opts [String] :franchise Business Unit code: Example: 80
  # @option opts [String] :date_from Start date to search shipments: Example: 2020-05-07T15:15:30Z
  # @option opts [String] :date_to End date to search shipments: Example: 2020-05-07T15:15:30Z
  # @return [ManifestResponseDto]
  describe 'pic_v1_shipments_delivery_manifest_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
