=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InflightOptionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InflightOptionsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InflightOptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InflightOptionsApi' do
    it 'should create an instance of InflightOptionsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::InflightOptionsApi)
    end
  end

  # unit tests for pic_v1_inflight_options_get
  # Inflight Options
  # Create a solution for a specific Solution Type from the provided values
  # @param authorization Bearer token obtained from SSO
  # @param observations Observations
  # @param solution_type Solution Type
  # @param [Hash] opts the optional parameters
  # @option opts [String] :expedition_code Expedition code
  # @option opts [String] :ref Reference
  # @option opts [String] :id_number Id Number
  # @option opts [String] :date Date on format: &#39;yyyy-MM-dd&#39;
  # @option opts [Integer] :center_code Center code
  # @option opts [String] :country_iso_code Country ISO Code
  # @option opts [String] :city_name City Name
  # @option opts [String] :street_type_code Street Type Code
  # @option opts [String] :street_name Street Name
  # @option opts [String] :postal_code Postal Code
  # @option opts [Integer] :city_code City Code
  # @option opts [String] :street_number_type_code Street Type Code
  # @option opts [String] :street_number Street Number
  # @option opts [String] :block block
  # @option opts [String] :floor floor
  # @option opts [String] :stairs stairs
  # @option opts [String] :door door
  # @option opts [String] :phone phone
  # @option opts [String] :name name
  # @option opts [String] :notification_mail Notificacion Mail
  # @option opts [Integer] :client_franchise Client Franchise
  # @option opts [String] :contact_person Contact Person
  # @option opts [String] :nif nif
  # @option opts [BOOLEAN] :sandbox sandbox
  # @return [GenericCreateResponseDto]
  describe 'pic_v1_inflight_options_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
