=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InternationalServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InternationalServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InternationalServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InternationalServicesApi' do
    it 'should create an instance of InternationalServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::InternationalServicesApi)
    end
  end

  # unit tests for pic_v1_output_platform_get
  # Get output platform
  # Get output Platform.
  # @param authorization Bearer token obtained from SSO
  # @param product_code Product
  # @param service_code Service
  # @param origin_depot Unity admin origin
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :destination_partner Destination agent
  # @option opts [Integer] :seur_center_id Seur center
  # @option opts [String] :customer_id Client
  # @option opts [String] :country_iso_code Country
  # @option opts [String] :postal_code Postal code
  # @option opts [Integer] :int_product_code International product
  # @option opts [Integer] :int_service_code International service
  # @option opts [String] :shipment_type Shipping type
  # @option opts [String] :city_name city name
  # @return [OutputPlatformResponse]
  describe 'pic_v1_output_platform_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for pic_v1_routing_oz_post
  # Calculate routing Operative Zones
  # Calculate routing operative zones.
  # @param authorization Bearer token obtained from SSO
  # @param input Operating areas
  # @param [Hash] opts the optional parameters
  # @return [RoutingOZResponse]
  describe 'pic_v1_routing_oz_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
