=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::LiveTrackingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LiveTrackingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::LiveTrackingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LiveTrackingApi' do
    it 'should create an instance of LiveTrackingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::LiveTrackingApi)
    end
  end

  # unit tests for pic_v1_livetracking_get
  # Get Live tracking from request
  # Get live tracking
  # @param authorization Bearer token obtained from SSO
  # @param id_number id number. Example: A480001
  # @param ref Reference. Example: REF0001234
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_number Account Number. Example: 123456
  # @option opts [String] :business_unit Business Unit. Example: 123456
  # @option opts [String] :ref_type Reference type. Example: REFERENCE
  # @option opts [BOOLEAN] :sandbox Enables sandbox. Example: false
  # @return [LiveTrackingResponse]
  describe 'pic_v1_livetracking_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
