=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PickupCentresServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PickupCentresServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PickupCentresServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PickupCentresServicesApi' do
    it 'should create an instance of PickupCentresServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PickupCentresServicesApi)
    end
  end

  # unit tests for pic_v1_pickups_get
  # Filter centres
  # Filter centres by country, postal code and city name
  # @param authorization Bearer token obtained from SSO
  # @param country_code Country code. Example: \&quot;ES\&quot;
  # @param postal_code Postal code: Example. \&quot;47270\&quot;
  # @param city_name City name: Example. \&quot;Cigales\&quot;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :centre_type Centre type: Example. \&quot;U\&quot;
  # @option opts [String] :exclude_code_sector Sector code excluded. Example: \&quot;400\&quot;
  # @return [CentresResponse]
  describe 'pic_v1_pickups_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
