=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::PodServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PodServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::PodServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PodServicesApi' do
    it 'should create an instance of PodServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::PodServicesApi)
    end
  end

  # unit tests for pic_v1_pods_get
  # Get pods
  # Filter pods by reference, idNumber or ccc
  # @param authorization Bearer token obtained from SSO
  # @param id_number Id Number code. Example: B03260684
  # @param ref Reference code. Example: 866075/4SHZQ6YLMEJ7BF
  # @param ref_type Reference type. Example: REFERENCE | ECB | PARCEL_NUMBER | SECOND_REFERENCE | PACK_REFERENCE
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_number Account Number. Example: 20855
  # @option opts [String] :business_unit Business Unit code: Example: 80
  # @option opts [BOOLEAN] :sandbox enables sandbox mode. Example: false
  # @option opts [String] :pod_type Pod type. Example: CONTENT | LINK. By default is CONTENT
  # @return [PodResponse]
  describe 'pic_v1_pods_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
