=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SituationsServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SituationsServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SituationsServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SituationsServicesApi' do
    it 'should create an instance of SituationsServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SituationsServicesApi)
    end
  end

  # unit tests for pic_v1_unfinished_situation_packs_post
  # Create a new unfinished situation by pack
  # Creates a new unfinished situation request by pack
  # @param [Hash] opts the optional parameters
  # @option opts [UnfinishedSituationRequest] :input The situation request to Process
  # @return [UnfinishedSituationResponse]
  describe 'pic_v1_unfinished_situation_packs_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for pic_v1_unfinished_situation_post
  # Create a new unfinished situation
  # Creates a new unfinished situation request
  # @param [Hash] opts the optional parameters
  # @option opts [UnfinishedSituationRequest] :input The situation request to Process
  # @return [UnfinishedSituationResponse]
  describe 'pic_v1_unfinished_situation_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
