=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TrackingServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TrackingServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TrackingServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TrackingServicesApi' do
    it 'should create an instance of TrackingServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TrackingServicesApi)
    end
  end

  # unit tests for pic_v1_tracking_services_extended_get
  # Get situations in extended format
  # Filter situations by reference, idNumber or ccc
  # @param authorization Bearer token obtained from SSO
  # @param id_number Id Number code. Example: B03260684
  # @param ref Reference code. Example: 866075/4SHZQ6YLMEJ7BF
  # @param ref_type Reference type. Example: REFERENCE | ECB | PARCEL_NUMBER | SECOND_REFERENCE | PACK_REFERENCE
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_number Account Number. Example: 20855
  # @option opts [String] :business_unit Business Unit code: Example: 80
  # @option opts [BOOLEAN] :sandbox run executions en mode sandbox Example: false
  # @return [ExtendedSituationResponse]
  describe 'pic_v1_tracking_services_extended_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for pic_v1_tracking_services_simplified_get
  # Get situations in simplified format
  # Filter situations by reference, idNumber or ccc
  # @param authorization Bearer token obtained from SSO
  # @param id_number Id Number code. Example: B03260684
  # @param ref Reference code. Example: 866075/4SHZQ6YLMEJ7BF
  # @param ref_type Reference type. Example: REFERENCE | ECB | PARCEL_NUMBER | SECOND_REFERENCE | PACK_REFERENCE
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_number Account Number. Example: 20855
  # @option opts [String] :business_unit Business Unit code: Example: 80
  # @option opts [BOOLEAN] :sandbox run in sandbox mode Example: false
  # @return [SimplifiedSituationResponse]
  describe 'pic_v1_tracking_services_simplified_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
