=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ValuateServicesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ValuateServicesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ValuateServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ValuateServicesApi' do
    it 'should create an instance of ValuateServicesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ValuateServicesApi)
    end
  end

  # unit tests for pic_v1_valuate_post
  # Valuate (National and International)
  # Valuate (National and International).
  # @param authorization Bearer token obtained from SSO
  # @param input Valuate
  # @param [Hash] opts the optional parameters
  # @return [ValuateResponseBody]
  describe 'pic_v1_valuate_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
