=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::UnfinishedSituationRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UnfinishedSituationRequest' do
  before do
    # run before each test
    @instance = SwaggerClient::UnfinishedSituationRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UnfinishedSituationRequest' do
    it 'should create an instance of UnfinishedSituationRequest' do
      expect(@instance).to be_instance_of(SwaggerClient::UnfinishedSituationRequest)
    end
  end
end
