=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'date'

module SwaggerClient
  class CentresData
    attr_accessor :depot

    attr_accessor :postal_code

    attr_accessor :code

    attr_accessor :name

    attr_accessor :type

    attr_accessor :address

    attr_accessor :city_name

    attr_accessor :pudo_id

    attr_accessor :latitude

    attr_accessor :longitude

    attr_accessor :street_type

    attr_accessor :street_number

    attr_accessor :additional_information

    attr_accessor :phone

    attr_accessor :weight_limit

    attr_accessor :night_service

    attr_accessor :opening_time

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'depot' => :'depot',
        :'postal_code' => :'postalCode',
        :'code' => :'code',
        :'name' => :'name',
        :'type' => :'type',
        :'address' => :'address',
        :'city_name' => :'cityName',
        :'pudo_id' => :'pudoId',
        :'latitude' => :'latitude',
        :'longitude' => :'longitude',
        :'street_type' => :'streetType',
        :'street_number' => :'streetNumber',
        :'additional_information' => :'additionalInformation',
        :'phone' => :'phone',
        :'weight_limit' => :'weightLimit',
        :'night_service' => :'nightService',
        :'opening_time' => :'openingTime'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'depot' => :'String',
        :'postal_code' => :'String',
        :'code' => :'String',
        :'name' => :'String',
        :'type' => :'String',
        :'address' => :'String',
        :'city_name' => :'String',
        :'pudo_id' => :'String',
        :'latitude' => :'String',
        :'longitude' => :'String',
        :'street_type' => :'String',
        :'street_number' => :'String',
        :'additional_information' => :'String',
        :'phone' => :'String',
        :'weight_limit' => :'String',
        :'night_service' => :'String',
        :'opening_time' => :'CentresWeekDays'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'depot')
        self.depot = attributes[:'depot']
      end

      if attributes.has_key?(:'postalCode')
        self.postal_code = attributes[:'postalCode']
      end

      if attributes.has_key?(:'code')
        self.code = attributes[:'code']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.has_key?(:'cityName')
        self.city_name = attributes[:'cityName']
      end

      if attributes.has_key?(:'pudoId')
        self.pudo_id = attributes[:'pudoId']
      end

      if attributes.has_key?(:'latitude')
        self.latitude = attributes[:'latitude']
      end

      if attributes.has_key?(:'longitude')
        self.longitude = attributes[:'longitude']
      end

      if attributes.has_key?(:'streetType')
        self.street_type = attributes[:'streetType']
      end

      if attributes.has_key?(:'streetNumber')
        self.street_number = attributes[:'streetNumber']
      end

      if attributes.has_key?(:'additionalInformation')
        self.additional_information = attributes[:'additionalInformation']
      end

      if attributes.has_key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.has_key?(:'weightLimit')
        self.weight_limit = attributes[:'weightLimit']
      end

      if attributes.has_key?(:'nightService')
        self.night_service = attributes[:'nightService']
      end

      if attributes.has_key?(:'openingTime')
        self.opening_time = attributes[:'openingTime']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          depot == o.depot &&
          postal_code == o.postal_code &&
          code == o.code &&
          name == o.name &&
          type == o.type &&
          address == o.address &&
          city_name == o.city_name &&
          pudo_id == o.pudo_id &&
          latitude == o.latitude &&
          longitude == o.longitude &&
          street_type == o.street_type &&
          street_number == o.street_number &&
          additional_information == o.additional_information &&
          phone == o.phone &&
          weight_limit == o.weight_limit &&
          night_service == o.night_service &&
          opening_time == o.opening_time
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [depot, postal_code, code, name, type, address, city_name, pudo_id, latitude, longitude, street_type, street_number, additional_information, phone, weight_limit, night_service, opening_time].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
