=begin
#SEUR Public API

#<b>INFORMATION ABOUT THE API</b>  <b>AUTH</b>  All requests must be accompanied by an authentication header with a 'Bearer ' obtained through the SSO token URL:  https://servicios.apipre.seur.io/pic_token  <i>Simple cURL Example</i>  curl -X POST --data-urlencode \"grant_type=client_credentials\" --data-urlencode \"client_id=<>\" --data-urlencode \"client_secret=<>\" https://servicios.apipre.seur.io/pic_token

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.39

=end

require 'date'

module SwaggerClient
  class ECBsAndParcelsRequestBody
    attr_accessor :bu

    attr_accessor :code_ic

    attr_accessor :service_code

    attr_accessor :service_product

    attr_accessor :postal_code

    attr_accessor :country

    attr_accessor :taric

    # Values: [\"DAP\", \"DDP\"]
    attr_accessor :inco_terms

    attr_accessor :customs_good_code

    attr_accessor :city

    attr_accessor :customer_id

    attr_accessor :counts

    attr_accessor :type

    attr_accessor :parcels

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'bu' => :'bu',
        :'code_ic' => :'codeIC',
        :'service_code' => :'serviceCode',
        :'service_product' => :'serviceProduct',
        :'postal_code' => :'postalCode',
        :'country' => :'country',
        :'taric' => :'taric',
        :'inco_terms' => :'incoTerms',
        :'customs_good_code' => :'customsGoodCode',
        :'city' => :'city',
        :'customer_id' => :'customerId',
        :'counts' => :'counts',
        :'type' => :'type',
        :'parcels' => :'parcels'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'bu' => :'String',
        :'code_ic' => :'Integer',
        :'service_code' => :'String',
        :'service_product' => :'String',
        :'postal_code' => :'String',
        :'country' => :'String',
        :'taric' => :'Integer',
        :'inco_terms' => :'String',
        :'customs_good_code' => :'String',
        :'city' => :'String',
        :'customer_id' => :'String',
        :'counts' => :'Integer',
        :'type' => :'String',
        :'parcels' => :'Array<Parcel>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'bu')
        self.bu = attributes[:'bu']
      end

      if attributes.has_key?(:'codeIC')
        self.code_ic = attributes[:'codeIC']
      end

      if attributes.has_key?(:'serviceCode')
        self.service_code = attributes[:'serviceCode']
      end

      if attributes.has_key?(:'serviceProduct')
        self.service_product = attributes[:'serviceProduct']
      end

      if attributes.has_key?(:'postalCode')
        self.postal_code = attributes[:'postalCode']
      end

      if attributes.has_key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.has_key?(:'taric')
        self.taric = attributes[:'taric']
      end

      if attributes.has_key?(:'incoTerms')
        self.inco_terms = attributes[:'incoTerms']
      end

      if attributes.has_key?(:'customsGoodCode')
        self.customs_good_code = attributes[:'customsGoodCode']
      end

      if attributes.has_key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.has_key?(:'customerId')
        self.customer_id = attributes[:'customerId']
      end

      if attributes.has_key?(:'counts')
        self.counts = attributes[:'counts']
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'parcels')
        if (value = attributes[:'parcels']).is_a?(Array)
          self.parcels = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @bu.nil?
        invalid_properties.push('invalid value for "bu", bu cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @bu.nil?
      return false if @type.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          bu == o.bu &&
          code_ic == o.code_ic &&
          service_code == o.service_code &&
          service_product == o.service_product &&
          postal_code == o.postal_code &&
          country == o.country &&
          taric == o.taric &&
          inco_terms == o.inco_terms &&
          customs_good_code == o.customs_good_code &&
          city == o.city &&
          customer_id == o.customer_id &&
          counts == o.counts &&
          type == o.type &&
          parcels == o.parcels
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [bu, code_ic, service_code, service_product, postal_code, country, taric, inco_terms, customs_good_code, city, customer_id, counts, type, parcels].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
